# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version, and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      # Convert notebooks to Python files before building docs
      - cd docs && python convert_notebooks.py

# Build documentation in the "docs/" directory with Sphinx
sphinx:
   configuration: docs/source/conf.py
   builder: html
   fail_on_warning: false

# Python requirements and installation
python:
   install:
   - requirements: docs/requirements.txt
   - method: pip
     path: .
        

